# SPDX-FileCopyrightText: Copyright 2025-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0

"""Shared compatibility surface for full and partial reachability review."""

from __future__ import annotations

from .dedup import Deduplicator
from .confirmer import VulnerabilityConfirmer
from .models import (
    FunctionNode,
    GlobalConstruct,
    ReachabilityGraph,
    ReachabilityPath,
    VulnerabilityFinding,
)
from .supplementary import SupplementaryAnalyzer
from .tracing import (
    PathTracer,
    SourceRootedPathTracer,
    _EXTRACTION_SYSTEM_PROMPT,
    _EXTRACTION_USER_TEMPLATE,
)
from .utils import (
    _C_CPP_EXTS,
    _VTYPE_FAMILY,
    _VULN_TO_CWE,
    _VULN_TYPE_ALIASES,
    _build_all_code,
    _build_chunked_code,
    _build_file_grouped_chunks,
    _build_file_grouped_node_chunks,
    _build_globals_code,
    _canonical_fields,
    _chat_model_kwargs,
    _chunked,
    _confidence_score,
    _dedupe_paths,
    _finding_code_context,
    _finding_file,
    _finding_function,
    _finding_line,
    _finding_text,
    _lookup_fn,
    _normalise_vuln_type,
    _number_lines,
    _path_key,
    _post_filter_findings,
    _read_function_body,
    _read_line_context,
    _safe_int,
    _same_file_ref,
    _severity_title,
    _string_list,
    _write_jsonl,
)

__all__ = [
    "Deduplicator",
    "FunctionNode",
    "GlobalConstruct",
    "PathTracer",
    "ReachabilityGraph",
    "ReachabilityPath",
    "SourceRootedPathTracer",
    "SupplementaryAnalyzer",
    "VulnerabilityConfirmer",
    "VulnerabilityFinding",
    "_C_CPP_EXTS",
    "_EXTRACTION_SYSTEM_PROMPT",
    "_EXTRACTION_USER_TEMPLATE",
    "_VTYPE_FAMILY",
    "_VULN_TO_CWE",
    "_VULN_TYPE_ALIASES",
    "_build_all_code",
    "_build_chunked_code",
    "_build_file_grouped_chunks",
    "_build_file_grouped_node_chunks",
    "_build_globals_code",
    "_canonical_fields",
    "_chat_model_kwargs",
    "_chunked",
    "_confidence_score",
    "_dedupe_paths",
    "_finding_code_context",
    "_finding_file",
    "_finding_function",
    "_finding_line",
    "_finding_text",
    "_lookup_fn",
    "_normalise_vuln_type",
    "_number_lines",
    "_path_key",
    "_post_filter_findings",
    "_read_function_body",
    "_read_line_context",
    "_safe_int",
    "_same_file_ref",
    "_severity_title",
    "_string_list",
    "_write_jsonl",
]
