# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0

MAX_CITATIONS = 12
ANALYZER_SEED_SYMBOL_LIMIT = 20

MAX_SECTIONS = 28
MAX_SYMBOL_TERMS = 3
DEFAULT_CAPTURE_MAX_LINES = 120
DEFAULT_CAPTURE_MAX_CHARS = 5000

FILE_WINDOW_RADIUS = 40

REPORTED_LINE_MAX_LINES = 20
REPORTED_LINE_MAX_CHARS = 1000

RELATED_GREP_MAX_LINES = 40
RELATED_GREP_MAX_CHARS = 1800

FALLBACK_GREP_MAX_LINES = 80
FALLBACK_GREP_MAX_CHARS = 3000

PROBE_GREP_MAX_LINES = RELATED_GREP_MAX_LINES
PROBE_GREP_MAX_CHARS = RELATED_GREP_MAX_CHARS

HIT_CONTEXT_RADIUS = 4
HIT_CONTEXT_MAX_LINES = 25
HIT_CONTEXT_MAX_CHARS = 1400

TARGETED_GREP_MAX_LINES = RELATED_GREP_MAX_LINES
TARGETED_GREP_MAX_CHARS = RELATED_GREP_MAX_CHARS
TARGETED_ROOT_GREP_MAX_LINES = 20
TARGETED_ROOT_GREP_MAX_CHARS = 1200
TARGETED_HIT_RADIUS = 3
TARGETED_HIT_CONTEXT_MAX_LINES = 20
TARGETED_HIT_CONTEXT_MAX_CHARS = 1200

MAX_TARGETS = 3
MAX_TARGETED_HITS = 4
MAX_TARGETED_CONTEXT_HITS = 2

ANALYZER_MAX_FALLBACK_TERMS = 4
MERGED_TERMS_LIMIT = 6

DEFAULT_MAX_FOLLOWUP_HITS = 12
ANALYZER_MAX_FOLLOWUP_HITS = 8

EVIDENCE_PACK_MAX_CHARS = 14000
RETRIEVAL_CONTEXT_MAX_CHARS = 14000

RELATED_PATH_INPUT_LIMIT = 8
FIND_NAME_MAX_RESULTS = 6
EXPANDED_RELATED_MAX = 12
READABLE_RELATED_MAX = 10
PROBE_FALLBACK_PATHS = 2
PROBE_HINT_HITS = 4
