name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write

jobs:
  analysis:
    uses: ossf/scorecard-action/.github/workflows/analysis.yml@v2
